"""Token definition used by tokenize and toc modules."""
# table of contents
#
# TODO TOKEN_TOC_CHAPTER_TITLE_START includes TOKEN_TOC_CHAPTER_NUMBER
# inside itself. need to assign multiple token types to some lines because of
# this reason
TOC_HEADER = 'TOKEN_TOC_HEADER'
TOC_SUMMARY_START = 'TOKEN_TOC_SUMMARY_START'
TOC_CHAPTER_NUMBER = 'TOKEN_TOC_CHAPTER_NUMBER'
TOC_CHAPTER_NUMBER_WITH_TITLE_CROSS_OFFICE = 'TOKEN_TOC_CHAPTER_NUMBER_WITH_TITLE_CROSS_OFFICE'
TOC_CHAPTER_NUMBER_WITH_TITLE_START = 'TOKEN_TOC_CHAPTER_NUMBER_WITH_TITLE_START'
TOC_CHAPTER_NUMBER_WITH_TITLE_CONTINUE = 'TOKEN_TOC_CHAPTER_NUMBER_WITH_TITLE_CONTINUE'

TOC_CHAPTER_OFFICE = 'TOKEN_TOC_CHAPTER_OFFICE'

TOC_CHAPTER_ITEM_ONE_LINE = 'TOKEN_TOC_CHAPTER_ITEM_ONE_LINE'
TOC_CHAPTER_ITEM_MULTI_LINE_START = 'TOKEN_TOC_CHAPTER_ITEM_MULTI_LINE_START'
TOC_CHAPTER_ITEM_MULTI_LINE_CONTINUE = 'TOKEN_TOC_CHAPTER_ITEM_MULTI_LINE_CONTINUE'
TOC_CHAPTER_ITEM_MULTI_LINE_END = 'TOKEN_TOC_CHAPTER_ITEM_MULTI_LINE_END'

# chapter topics
SUMMARY_HEADER = 'TOKEN_SUMMARY_HEADER'  # "תקצירים"

CHAPTER_NUMBER = 'TOKEN_CHAPTER_NUMBER'  # "פרק ראשון"

CHAPTER_OFFICE_NAME = 'TOKEN_CHAPTER_OFFICE_NAME'

CHAPTER_TOPIC_TITLE_START = 'TOKEN_CHAPTER_TOPIC_TITLE_START'
CHAPTER_TOPIC_TITLE_CONTINUE = 'TOKEN_CHAPTER_TOPIC_TITLE_CONTINUE'

CHAPTER_TOPIC_DISCUSSED_OFFICES_START = 'TOKEN_CHAPTER_TOPIC_DISCUSSED_OFFICES_START'
CHAPTER_TOPIC_DISCUSSED_OFFICES_CONTINUE = 'TOKEN_CHAPTER_TOPIC_DISCUSSED_OFFICES_CONTINUE'

# defects
DEFECT_HEADER = 'TOKEN_DEFECT_HEADER'
DEFECT_BODY_START = 'TOKEN_DEFECT_BODY_START'
DEFECT_BODY_CONTINUE = 'TOKEN_DEFECT_BODY_CONTINUE'

# defect replies
DEFECT_REPLY_HEADER = 'TOKEN_DEFECT_REPLY_HEADER'
DEFECT_REPLY_OFFICE_NAME = 'TOKEN_DEFECT_REPLY_OFFICE_NAME'
DEFECT_REPLY_BODY_START = 'TOKEN_DEFECT_REPLY_BODY_START'
DEFECT_REPLY_BODY_CONTINUE = 'TOKEN_DEFECT_REPLY_BODY_CONTINUE'
