"""Token definition used by tokenize and toc modules."""
# table of contents
#
# TODO TOKEN_TOC_CHAPTER_TITLE_START includes TOKEN_TOC_CHAPTER_NUMBER
# inside itself. need to assign multiple token types to some lines because of
# this reason
TOKEN_TOC_HEADER = 'TOKEN_TOC_HEADER'
TOKEN_TOC_SUMMARY_START = 'TOKEN_TOC_SUMMARY_START'
TOKEN_TOC_CHAPTER_NUMBER = 'TOKEN_TOC_CHAPTER_NUMBER'
TOKEN_TOC_CHAPTER_TITLE_START = 'TOKEN_TOC_CHAPTER_TITLE_START'
TOKEN_TOC_CHAPTER_TITLE_CONTINUE = 'TOKEN_TOC_CHAPTER_TITLE_CONTINUE'

TOKEN_TOC_CHAPTER_OFFICE = 'TOKEN_TOC_CHAPTER_OFFICE'

TOKEN_TOC_CHAPTER_ITEM_START = 'TOKEN_TOC_CHAPTER_ITEM_START'
TOKEN_TOC_CHAPTER_ITEM_CONTINUE = 'TOKEN_TOC_CHAPTER_ITEM_CONTINUE'

# chapter topics
TOKEN_SUMMARY_HEADER = 'TOKEN_SUMMARY_HEADER'  # "תקצירים"

TOKEN_CHAPTER_HEADER = 'TOKEN_CHAPTER_HEADER'  # "פרק ראשון"

TOKEN_CHAPTER_OFFICE_NAME = 'TOKEN_CHAPTER_OFFICE_NAME'

TOKEN_CHAPTER_TOPIC_TITLE_START = 'TOKEN_CHAPTER_TOPIC_TITLE_START'
TOKEN_CHAPTER_TOPIC_TITLE_CONTINUE = 'TOKEN_CHAPTER_TOPIC_TITLE_CONTINUE'

TOKEN_CHAPTER_TOPIC_DISCUSSED_OFFICES_START = 'TOKEN_CHAPTER_TOPIC_DISCUSSED_OFFICES_START'
TOKEN_CHAPTER_TOPIC_DISCUSSED_OFFICES_CONTINUE = 'TOKEN_CHAPTER_TOPIC_DISCUSSED_OFFICES_CONTINUE'

# defects
TOKEN_DEFECT_HEADER = 'TOKEN_DEFECT_HEADER'
TOKEN_DEFECT_BODY_START = 'TOKEN_DEFECT_BODY_START'
TOKEN_DEFECT_BODY_CONTINUE = 'TOKEN_DEFECT_BODY_CONTINUE'

# defect replies
TOKEN_DEFECT_REPLY_HEADER = 'TOKEN_DEFECT_REPLY_HEADER'
TOKEN_DEFECT_REPLY_OFFICE_NAME = 'TOKEN_DEFECT_REPLY_OFFICE_NAME'
TOKEN_DEFECT_REPLY_BODY_START = 'TOKEN_DEFECT_REPLY_BODY_START'
TOKEN_DEFECT_REPLY_BODY_CONTINUE = 'TOKEN_DEFECT_REPLY_BODY_CONTINUE'
